name: Update Steps(xiaomi)

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装第三方库
      run: pip install requests
    - name: 更新步数 152***
      run: |
        user='${{ secrets.USER152 }}'
        password='${{ secrets.PWD152 }}'
        step='${{ secrets.STEP }}'
        sckey='${{ secrets.SCKEY }}'
        
        python3 xiaomi.py <<EOF
        ${user}
        ${password}
        ${step}
        ${sckey}
        EOF
    - name: 更新步数 183***
      run: |
        user='${{ secrets.USER183 }}'
        password='${{ secrets.PWD183 }}'
        step='${{ secrets.STEP }}'
        sckey='${{ secrets.SCKEY }}'
        
        python3 xiaomi.py <<EOF
        ${user}
        ${password}
        ${step}
        ${sckey}
        EOF
    - name: 更新步数 187***
      run: |
        user='${{ secrets.USER187 }}'
        password='${{ secrets.PWD187 }}'
        step='${{ secrets.STEP }}'
        sckey='${{ secrets.SCKEY }}'
        
        python3 xiaomi.py <<EOF
        ${user}
        ${password}
        ${step}
        ${sckey}
        EOF
